# Health Stats Part 4: Waist 2 Hip Ratios - Pandas Only

<!--- Write an explanation of the Waist To Hips Ratio statistic used by health professionals. Please include an explanation of what it is used for, exactly how it is calculated, and how to interpret the results. Note: Formmatting matters. Make this as professional as you can using Markdown.  --->
Misleading information provided by follow up changes in waist:hip ratio in woman followed over 20 years. An increase in waist to hip ratio means that it is stable overtime. [Research Gate](https://www.researchgate.net/figure/Misleading-information-provided-by-follow-up-of-changes-in-waisthip-ratio-in-woman_fig2_12069120)


$ ratio_{w2h} = \frac{w}-{h} $

<img src = 'https://www.researchgate.net/profile/Isabelle_Lemieux/publication/12069120/figure/fig2/AS:394585634295819@1471087954685/Misleading-information-provided-by-follow-up-of-changes-in-waisthip-ratio-in-woman.png' />

## Source Data

<!--- Replace the text below with a Markdown bullet list that defines the columns of the CSV file. Be sure to indicate the data type for each column. --->

- Column 1:
    - ID: unique identifier for each person
        - Float
- Column 2:
    - Waist: measurment of a waist
        - Float

- Column 3:
    - Hip: measurement of hip 
        - Float

- Coulumn 4:
    - Gender: categorize into male and female  
        - String

## Data Import

In [13]:
import pandas as pd
w2h_df = pd.read_csv("w2h_data.csv")
w2h_df

    ID  Waist  Hip Gender
0    1     30   32      M
1    2     32   37      M
2    3     30   36      M
3    4     33   39      M
4    5     29   33      M
5    6     32   38      M
6    7     33   42      M
7    8     30   40      M
8    9     30   37      M
9   10     32   39      M
10  11     24   35      F
11  12     25   37      F
12  13     24   37      F
13  14     22   34      F
14  15     26   38      F
15  16     26   37      F
16  17     25   38      F
17  18     26   37      F
18  19     28   40      F
19  20     23   35      F

## Calculations

In [21]:
# Goal: For each row of data calculate and store the w2h_ratio and shape.
# Step 1: Make sure the columns are in correct data types - refer to previous parts for the correct data types
w2h_df.dtypes

# Step 2: calculate the 'W2H_Ratio' column using the 'Waist' and 'Hip' columns
w2h_df['w2h_ratio'] = w2h_df['Waist']/w2h_df['Hip']
w2h_df

# Step 3: Create the `Shape` column based on the values of the `W2H_Ratio` column - refer to previous partsfor the logic


w2h_df['Shape']= 'Pear'
w2h_df.loc[(w2h_df['Gender'] == 'M') & (w2h_df['w2h_ratio']>0.9) | (w2h_df['Gender'] == 'F') & (w2h_df['w2h_ratio']>0.8),'Shape']='Apple'

## Output

In [23]:
# Goal: pretty print the rows as an HTML table


# Save the DF to a file './complete_w2h.csv'
w2h_df

    ID  Waist  Hip Gender  Shape  w2h_ratio
0    1     30   32      M  Apple   0.937500
1    2     32   37      M   Pear   0.864865
2    3     30   36      M   Pear   0.833333
3    4     33   39      M   Pear   0.846154
4    5     29   33      M   Pear   0.878788
5    6     32   38      M   Pear   0.842105
6    7     33   42      M   Pear   0.785714
7    8     30   40      M   Pear   0.750000
8    9     30   37      M   Pear   0.810811
9   10     32   39      M   Pear   0.820513
10  11     24   35      F   Pear   0.685714
11  12     25   37      F   Pear   0.675676
12  13     24   37      F   Pear   0.648649
13  14     22   34      F   Pear   0.647059
14  15     26   38      F   Pear   0.684211
15  16     26   37      F   Pear   0.702703
16  17     25   38      F   Pear   0.657895
17  18     26   37      F   Pear   0.702703
18  19     28   40      F   Pear   0.700000
19  20     23   35      F   Pear   0.657143

## Lessons Learned

Have you noticed in the previous two parts, how much code we have written? Have you also note how little code we have written in this part, with the help of Pandas? 

This is the reason why we want to use Pandas to handle the data we use for analytics.